# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_download.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66ile_download.proto\x12\x07\x66\x64l_svc\"\x89\x01\n\x13\x46ileDownloadMessage\x12\x39\n\trequester\x18\x01 \x01(\x0b\x32&.fdl_svc.FileDownloadMessage.Requester\x12\r\n\x05\x66iles\x18\x02 \x03(\t\x1a(\n\tRequester\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\tb\x06proto3')



_FILEDOWNLOADMESSAGE = DESCRIPTOR.message_types_by_name['FileDownloadMessage']
_FILEDOWNLOADMESSAGE_REQUESTER = _FILEDOWNLOADMESSAGE.nested_types_by_name['Requester']
FileDownloadMessage = _reflection.GeneratedProtocolMessageType('FileDownloadMessage', (_message.Message,), {

  'Requester' : _reflection.GeneratedProtocolMessageType('Requester', (_message.Message,), {
    'DESCRIPTOR' : _FILEDOWNLOADMESSAGE_REQUESTER,
    '__module__' : 'file_download_pb2'
    # @@protoc_insertion_point(class_scope:fdl_svc.FileDownloadMessage.Requester)
    })
  ,
  'DESCRIPTOR' : _FILEDOWNLOADMESSAGE,
  '__module__' : 'file_download_pb2'
  # @@protoc_insertion_point(class_scope:fdl_svc.FileDownloadMessage)
  })
_sym_db.RegisterMessage(FileDownloadMessage)
_sym_db.RegisterMessage(FileDownloadMessage.Requester)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FILEDOWNLOADMESSAGE._serialized_start=33
  _FILEDOWNLOADMESSAGE._serialized_end=170
  _FILEDOWNLOADMESSAGE_REQUESTER._serialized_start=130
  _FILEDOWNLOADMESSAGE_REQUESTER._serialized_end=170
# @@protoc_insertion_point(module_scope)
