# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_download.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import motrpac_backend_utils.proto.common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13\x66ile_download.proto\x12\x07\x66\x64l_svc\x1a\x0c\x63ommon.proto"K\n\x13\x46ileDownloadMessage\x12%\n\trequester\x18\x01 \x01(\x0b\x32\x12.fdl_svc.Requester\x12\r\n\x05\x66iles\x18\x02 \x03(\tb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "file_download_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_FILEDOWNLOADMESSAGE"]._serialized_start = 46
    _globals["_FILEDOWNLOADMESSAGE"]._serialized_end = 121
# @@protoc_insertion_point(module_scope)
