"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class FileDownloadMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class Requester(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        EMAIL_FIELD_NUMBER: builtins.int
        NAME_FIELD_NUMBER: builtins.int
        email: typing.Text
        name: typing.Text
        def __init__(self,
            *,
            email: typing.Text = ...,
            name: typing.Text = ...,
            ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["email",b"email","name",b"name"]) -> None: ...

    REQUESTER_FIELD_NUMBER: builtins.int
    FILES_FIELD_NUMBER: builtins.int
    @property
    def requester(self) -> global___FileDownloadMessage.Requester: ...
    @property
    def files(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    def __init__(self,
        *,
        requester: typing.Optional[global___FileDownloadMessage.Requester] = ...,
        files: typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["requester",b"requester"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["files",b"files","requester",b"requester"]) -> None: ...
global___FileDownloadMessage = FileDownloadMessage
