# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_download.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'file_download.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66ile_download.proto\x12\x07\x66\x64l_svc\"\xf1\x01\n\x13\x46ileDownloadMessage\x12\x39\n\trequester\x18\x01 \x01(\x0b\x32&.fdl_svc.FileDownloadMessage.Requester\x12\x30\n\x05\x66iles\x18\x02 \x03(\x0b\x32!.fdl_svc.FileDownloadMessage.File\x1a@\n\tRequester\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x02id\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x05\n\x03_id\x1a+\n\x04\x46ile\x12\x0e\n\x06object\x18\x01 \x01(\t\x12\x13\n\x0bobject_size\x18\x02 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_download_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEDOWNLOADMESSAGE']._serialized_start=33
  _globals['_FILEDOWNLOADMESSAGE']._serialized_end=274
  _globals['_FILEDOWNLOADMESSAGE_REQUESTER']._serialized_start=165
  _globals['_FILEDOWNLOADMESSAGE_REQUESTER']._serialized_end=229
  _globals['_FILEDOWNLOADMESSAGE_FILE']._serialized_start=231
  _globals['_FILEDOWNLOADMESSAGE_FILE']._serialized_end=274
# @@protoc_insertion_point(module_scope)
